# Generated by Django 5.1.3 on 2025-03-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
