# Generated by Django 5.0.6 on 2024-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='chassis',
            field=models.CharField(blank=True, choices=[('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='free_installation',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
