# Generated by Django 5.0.6 on 2024-06-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_products_chassis_products_free_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.catalogue'),
        ),
    ]
