# Generated by Django 5.1.3 on 2025-03-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_car_model_products_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_products', to='base.car_model'),
        ),
    ]
