# Generated by Django 5.1.3 on 2025-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_products_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
