# Generated by Django 5.1.3 on 2025-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_products_original_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_model',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='car_model',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
