# Generated by Django 5.1.3 on 2025-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_car_model_options_car_model_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
