# Generated by Django 5.1.3 on 2025-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_quantity',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
